### ISSUE TITLE
Does not work with pnpm as package manager

### ISSUE THREAD

**Issue by CodeCakePie** [simonnepomuk/monorepo#3]
I am currently adopting to this adapter and I am having a tough time getting it to work, due to the required packages.

In the first try it was missing firebase-functions, so I added these by hand.
Next try tslib was missing, added again by hand.

Now it seemed to work fine, just to get "An unexpected error has occurred."

Looking at the firebase-debug.log I see the following:

```
TypeError: Cannot read properties of undefined (reading 'service')
    at /usr/local/share/npm-global/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:198:113
    at Array.map (<anonymous>)
    at loadExistingBackend (/usr/local/share/npm-global/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:198:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.existingBackend (/usr/local/share/npm-global/lib/node_modules/firebase-tools/lib/deploy/functions/backend.js:174:9)
    at async prepare (/usr/local/share/npm-global/lib/node_modules/firebase-tools/lib/deploy/functions/prepare.js:151:115)
    at async chain (/usr/local/share/npm-global/lib/node_modules/firebase-tools/lib/deploy/index.js:35:9)
    at async deploy (/usr/local/share/npm-global/lib/node_modules/firebase-tools/lib/deploy/index.js:79:5)
[error] 
[error] Error: An unexpected error has occurred.
```

I guess this is related to pnpm

**Comment by simonnepomuk** [comment]
Can you share your `firebase.json` and `svelte.config.js`?

**Comment by CodeCakePie** [comment]
sure

```
import adapter from 'sveltekit-adapter-firebase';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: [
		preprocess({
			postcss: true
		})
	],
	kit: {
		adapter: adapter({
			functionOptions: {
				region: 'europe-west1'
			}
		})
	}
};

export default config;
```

```
{
  "hosting": {
    "public": "build",
    "ignore": [
      "**/.firebase/**"
    ],
    "cleanUrls": true,
    "rewrites": [
      {
        "source": "**",
        "function": "handler",
        "region": "europe-west1"
      }
    ]
  },
  "functions": [
    {
      "source": "build"
    }
  ]
}
```

**Comment by CodeCakePie** [comment]
I have to correct myself: pnpm is not the issue here, its also not working with yarn, which should resolve the packages as the npm would.
I will try to add the same dependencies as in your example 🤔

**Comment by simonnepomuk** [comment]
Sorry this auto-closed while merging the PR that addresses the missing dependencies. Using the newest version `0.1.11` i can not reproduce this anymore. Did you run `firebase init` and what command leads to the output you posted above? If you can provide a reproduction repo I will investigate this further.

**Comment by CodeCakePie** [comment]
I updated to 0.1.11 but the function still fails do deploy according to the cloud console.
I was able to find some better log message though:
```
Detailed stack trace: Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@sveltejs/kit' imported from /workspace/.firebase/shims.js
```

Looking at the build/package.json the @sveltejs/kit module is not included and the shims.js file is trying to access it, but not sure if that is the problem.

**Comment by simonnepomuk** [comment]
Hey, thanks for the debugging :) Not so pretty workaround would be to include the SvelteKit dependency into the generated production package.json but we should bundle the shims provided by SvelteKit instead of importing them to keep the production bundle smaller. I'm currently looking into bundling with esbuild or rollup, but the plugins provided by Nx (which is used to power the monorepo) have some limitations. I'll try to invest some time over the course of next week.

**Comment by simonnepomuk** [comment]
Should be fixed with `0.1.12`

**Comment by CodeCakePie** [comment]
There is still an issue: The whole .firebase folder of the build result is not uploaded to firebase. I have just downloaded the source of the uploaded cloudfunction and it only containes the _app folder and all files within the build folder but not the .firebase folder. Maybe this has something to do with macos?

**Comment by CodeCakePie** [comment]
@simonnepomuk should I create a new issue for this or should this keept in this issue? 😄

**Comment by CodeCakePie** [comment]
The issue is related to linux it seems, renaming it to _firebase fixes this issue, so I would suggest to change the .firebase folder to _firebase.
But there is another isse: the node_modules folder is missing in the cloud function, even though it is present on my local machine 🤔

**Comment by CodeCakePie** [comment]
Ok, it seems like I am just stupid and the .firebase folder was also there but it was hidden in finder, sorry!
But the problem remains that the npm package I need is not working as expected:

```
file:///workspace/_firebase/server/chunks/firebase.js:5
import { authState } from "rxfire/auth";
 ^^^^^^^^^
SyntaxError: Named export 'authState' not found. The requested module 'rxfire/auth' is a CommonJS module, which may not support all module.exports as named exports.
```
Thats the error I get from the gcp console. It seems like the node_modules are present but not in the correct format. I use node 16 on my local machine and in the cloud function. Do you have any idea? 🤔

**Comment by CodeCakePie** [comment]
Seems like this [issue](https://github.com/FirebaseExtended/rxfire/issues/52) could also be related to the specific library which doesn't make any sense to me. It used to work with the other adapter I was using 🤔

**Comment by soupman99** [comment]
@simonnepomuk any update on this?  I'm running into a similar issue but my error is:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'devalue' imported from /workspace/.firebase/server/index.js
